export const routes = {
    home: "/",
    about: "/about",
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    product: "/product",
    productDetail: "/product/:id",
    review: "product/:id/review",
    cart: "/cart",
    checkout: "/checkout",
    quiz:"/quiz",
    startQuiz:"/quiz/start",
    contact: "/contact",
    service: "/service",
}