export const routes = {
    home: '/',
    about: '/about',
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    product: '/product',
    productDetail: '/product/:id',
    review: '/product/:id/review',
    contact: '/contact',
    service: '/service',
    faq: '/faq',
    cart: '/cart',
    checkout: '/checkout',
    orderConfirmPage: '/confirmOrder',
    event: '/event',
    aboutUs: '/about-us',
    profile: '/profile',
    quiz: '/quiz',
    startQuiz: '/quiz/start',
    manageOrder: '/manage-order',
    manageComment: '/manage-comment',
    manageAccount: '/manage-account',
    manageEvent: '/manage-event',
    resultQuiz: '/your-skin-type-result',
    paymentReturn: '/payment-return',
    notfound: '/404',
    restricted: '/restricted',
    
};
