// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250114123755_AutoMigration_20250114193747")]
    partial class AutoMigration_20250114193747
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Property<long>("AccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("accID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccId"));

                    b.Property<short>("AccStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("accStatusID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("'255'::character varying");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("roleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("AccId")
                        .HasName("Account_pkey");

                    b.HasIndex("AccStatusId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "account_username_unique")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccountStatus", b =>
                {
                    b.Property<short>("AccStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("accStatusID");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("statusName");

                    b.HasKey("AccStatusId")
                        .HasName("AccountStatus_pkey");

                    b.ToTable("AccountStatus", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("addressID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AddressId"));

                    b.Property<string>("AddDetail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("addDetail");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("country");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("district");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("isDefault");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ward");

                    b.HasKey("AddressId")
                        .HasName("Address_pkey");

                    b.HasIndex("UsrId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AnswerUser", b =>
                {
                    b.Property<long>("AndId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("andID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AndId"));

                    b.Property<short>("KeyId")
                        .HasColumnType("smallint")
                        .HasColumnName("keyID");

                    b.Property<short>("QuestionId")
                        .HasColumnType("smallint")
                        .HasColumnName("questionID");

                    b.HasKey("AndId")
                        .HasName("AnswerUser_pkey");

                    b.HasIndex("KeyId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerUser", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<long>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("brandID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BrandId"));

                    b.Property<string>("BrandDesc")
                        .HasColumnType("text")
                        .HasColumnName("brandDesc");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brandName");

                    b.Property<string>("BrandOrigin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brandOrigin");

                    b.Property<bool>("BrandStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("brandStatus");

                    b.HasKey("BrandId")
                        .HasName("Brand_pkey");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CategoryProduct", b =>
                {
                    b.Property<long>("CateProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cateProdID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CateProdId"));

                    b.Property<string>("CateProdName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cateProdName");

                    b.Property<bool>("CateProdStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("cateProdStatus");

                    b.HasKey("CateProdId")
                        .HasName("CategoryProduct_pkey");

                    b.ToTable("CategoryProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CategoryQuestion", b =>
                {
                    b.Property<short>("CateQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("cateQuestionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("CateQuestionId"));

                    b.Property<string>("CateDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cateDesc");

                    b.Property<string>("CateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cateName");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.HasKey("CateQuestionId")
                        .HasName("CategoryQuestion_pkey");

                    b.ToTable("CategoryQuestion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Property<long>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("commentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CommentId"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commentContent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("CommentId")
                        .HasName("Comment_pkey");

                    b.HasIndex("ProdId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeliveryDetail", b =>
                {
                    b.Property<long>("DeliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("deliID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliId"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("addressID");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createAt");

                    b.Property<string>("DeliPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deliPhoneNumber");

                    b.Property<long>("DeliServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("deliServiceID");

                    b.Property<bool>("DeliStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("deliStatus")
                        .HasComment("Just manage 2 status: Success / False");

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.HasKey("DeliId")
                        .HasName("DeliveryDetail_pkey");

                    b.HasIndex("AddressId");

                    b.HasIndex("DeliServiceId");

                    b.HasIndex("OrdId");

                    b.ToTable("DeliveryDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeliveryService", b =>
                {
                    b.Property<long>("DeliServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DeliServiceID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliServiceId"));

                    b.Property<string>("ContactService")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contactService");

                    b.Property<string>("DeliServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("DeliServiceStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("deliServiceStatus");

                    b.HasKey("DeliServiceId")
                        .HasName("DeliveryService_pkey");

                    b.ToTable("DeliveryService", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("discountPercent");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("endTime");

                    b.Property<string>("EventDesc")
                        .HasColumnType("text")
                        .HasColumnName("eventDesc");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("eventName");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("startTime");

                    b.HasKey("EventId")
                        .HasName("Event_pkey");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EventDetail", b =>
                {
                    b.Property<long>("EventDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eventDetailID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventDetailId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("productID");

                    b.HasKey("EventDetailId")
                        .HasName("EventDetail_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("ProductId");

                    b.ToTable("EventDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KeyQuestion", b =>
                {
                    b.Property<short>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("keyID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("KeyId"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<string>("KeyContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyContent");

                    b.Property<short>("KeyScore")
                        .HasColumnType("smallint")
                        .HasColumnName("keyScore");

                    b.Property<short>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("questionID");

                    b.HasKey("KeyId")
                        .HasName("KeyQuestion_pkey");

                    b.HasIndex("QuestionId");

                    b.ToTable("KeyQuestion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<long>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrdId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    b.Property<DateTime>("OrdDate")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("ordDate");

                    b.Property<short>("OrdStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("ordStatusID");

                    b.Property<double>("TotalOrdPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("totalOrdPrice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("OrdId")
                        .HasName("Order_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("OrdStatusId");

                    b.HasIndex("UsrId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("OrdDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordDetailID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrdDetailId"));

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<double>("SellPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("sellPrice");

                    b.HasKey("OrdDetailId")
                        .HasName("OrderDetail_pkey");

                    b.HasIndex("OrdId");

                    b.HasIndex("ProdId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderLog", b =>
                {
                    b.Property<long>("OrdLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordLogID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrdLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<short>("NewStatusOrdId")
                        .HasColumnType("smallint")
                        .HasColumnName("newStatusOrdID");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("OrdLogId")
                        .HasName("OrderLog_pkey");

                    b.HasIndex("NewStatusOrdId");

                    b.HasIndex("OrdId");

                    b.ToTable("OrderLog", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderStatus", b =>
                {
                    b.Property<short>("OrdStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("ordStatusID");

                    b.Property<string>("OrdStatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ordStatusName");

                    b.HasKey("OrdStatusId")
                        .HasName("OrderStatus_pkey");

                    b.ToTable("OrderStatus", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("productID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductId"));

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brandID");

                    b.Property<long>("CateId")
                        .HasColumnType("bigint")
                        .HasColumnName("cateID");

                    b.Property<double>("CostPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasColumnName("costPrice")
                        .HasDefaultValueSql("'0'::double precision");

                    b.Property<string>("ProductDesc")
                        .HasColumnType("text")
                        .HasColumnName("productDesc");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("productName");

                    b.Property<double>("SellPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasColumnName("sellPrice")
                        .HasDefaultValueSql("'0'::double precision");

                    b.Property<int>("Stocks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stocks");

                    b.Property<double?>("TotalRating")
                        .HasColumnType("double precision")
                        .HasColumnName("totalRating");

                    b.HasKey("ProductId")
                        .HasName("Product_pkey");

                    b.HasIndex("BrandId");

                    b.HasIndex("CateId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.Property<long>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("productImageID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductImageId"));

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("productID");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("productImageUrl");

                    b.HasKey("ProductImageId")
                        .HasName("ProductImage_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<short>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("questionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("QuestionId"));

                    b.Property<long>("AnsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ansID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnsId"));

                    b.Property<short>("CateQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("cateQuestionID");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questionContent");

                    b.HasKey("QuestionId")
                        .HasName("Question_pkey");

                    b.HasIndex("CateQuestionId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RatingProduct", b =>
                {
                    b.Property<long>("RatingProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ratingProdID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RatingProdId"));

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("RatingProdId")
                        .HasName("RatingProduct_pkey");

                    b.HasIndex("ProdId");

                    b.ToTable("RatingProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultSkinTest", b =>
                {
                    b.Property<long>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("resultID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ResultId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createAt");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isDefault");

                    b.Property<short>("Odscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ODScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("OilyDryScore");

                    b.Property<short>("Pnpscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("PNPScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("PigmentedNonPigmentedScore");

                    b.Property<short>("SkinTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("skinTypeID");

                    b.Property<short>("Srscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("SRScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("SensitiveResistantScore");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint")
                        .HasColumnName("testID");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<short>("Wtscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("WTScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("WrinkledTightScore");

                    b.HasKey("ResultId")
                        .HasName("ResultSkinTest_pkey");

                    b.HasIndex("SkinTypeId");

                    b.HasIndex("TestId");

                    b.HasIndex("UsrId");

                    b.ToTable("ResultSkinTest", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnProduct", b =>
                {
                    b.Property<long>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("returnID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReturnId"));

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("returnDate");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("ReturnId")
                        .HasName("ReturnProduct_pkey");

                    b.HasIndex("OrdId");

                    b.HasIndex("UsrId");

                    b.ToTable("ReturnProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnProductDetail", b =>
                {
                    b.Property<long>("ReturnProductDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("returnProductDetailID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReturnProductDetailId"));

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<long>("ReturnId")
                        .HasColumnType("bigint")
                        .HasColumnName("returnID");

                    b.Property<string>("ReturnImgUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("returnImgUrl");

                    b.Property<short>("ReturnQuantity")
                        .HasColumnType("smallint")
                        .HasColumnName("returnQuantity");

                    b.HasKey("ReturnProductDetailId")
                        .HasName("ReturnProductDetail_pkey");

                    b.HasIndex("ProdId");

                    b.HasIndex("ReturnId");

                    b.ToTable("ReturnProductDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("roleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("roleName");

                    b.Property<bool>("RoleStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("roleStatus");

                    b.HasKey("RoleId")
                        .HasName("Role_pkey");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SkinType", b =>
                {
                    b.Property<short>("SkinTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("skinTypeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("SkinTypeId"));

                    b.Property<string>("SkinTypeCodes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("skinTypeCodes")
                        .HasComment("Mã loại da (ví dụ: \"OSPT\", \"DRNW\").");

                    b.Property<string>("SkinTypeDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skinTypeDesc")
                        .HasComment("Mô tả chi tiết về loại da.");

                    b.Property<string>("SkinTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("skinTypeName")
                        .HasComment("Tên loại da đầy đủ (ví dụ: \"Oily, Sensitive, Pigmented, Tight\").");

                    b.HasKey("SkinTypeId")
                        .HasName("SkinType_pkey");

                    b.ToTable("SkinType", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SkinTypeTest", b =>
                {
                    b.Property<long>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("testID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TestId"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<long>("CreatedByUsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("createdByUsrID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CreatedByUsrId"));

                    b.Property<string>("TestDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("testDesc");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("testName");

                    b.HasKey("TestId")
                        .HasName("SkinTypeTest_pkey");

                    b.ToTable("SkinTypeTest", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SkinTypeTestDetail", b =>
                {
                    b.Property<long>("DetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("detailID");

                    b.Property<short>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("questionID");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint")
                        .HasColumnName("testID");

                    b.HasKey("DetailId")
                        .HasName("SkinTypeTestDetail_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestId");

                    b.ToTable("SkinTypeTestDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UseFor", b =>
                {
                    b.Property<long>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("recID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecId"));

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<short>("SkinTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("skinTypeID");

                    b.HasKey("RecId")
                        .HasName("UseFor_pkey");

                    b.HasIndex("ProdId");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("UseFor", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("UsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatarUrl");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("coverUrl");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createAt");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerifyToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("emailVerifyToken");

                    b.Property<string>("ForgotPasswordToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("forgotPasswordToken");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gender");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updateAt");

                    b.HasKey("UsrId")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "Email" }, "user_email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "EmailVerifyToken" }, "user_emailverifytoken_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "ForgotPasswordToken" }, "user_forgotpasswordtoken_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "user_phone_unique")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.Property<long>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("voucherID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VoucherId"));

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<string>("VoucherDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voucherDesc");

                    b.Property<double>("VoucherDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("voucherDiscount");

                    b.HasKey("VoucherId")
                        .HasName("Voucher_pkey");

                    b.HasIndex("UsrId");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WarantyOrder", b =>
                {
                    b.Property<long>("WarantyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("warantyID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WarantyId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createAt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("endDate");

                    b.Property<long>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.HasKey("WarantyId")
                        .HasName("WarantyOrder_pkey");

                    b.HasIndex("OrdId");

                    b.ToTable("WarantyOrder", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.HasOne("Domain.Entities.AccountStatus", "AccStatus")
                        .WithMany("Accounts")
                        .HasForeignKey("AccStatusId")
                        .IsRequired()
                        .HasConstraintName("account_accstatusid_foreign");

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("account_roleid_foreign");

                    b.Navigation("AccStatus");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("Addresses")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("address_usrid_foreign");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.AnswerUser", b =>
                {
                    b.HasOne("Domain.Entities.KeyQuestion", "Key")
                        .WithMany("AnswerUsers")
                        .HasForeignKey("KeyId")
                        .IsRequired()
                        .HasConstraintName("answeruser_keyid_foreign");

                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("AnswerUsers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("answeruser_questionid_foreign");

                    b.Navigation("Key");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("Comments")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("comment_prodid_foreign");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("Domain.Entities.DeliveryDetail", b =>
                {
                    b.HasOne("Domain.Entities.Address", "Address")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("deliverydetail_addressid_foreign");

                    b.HasOne("Domain.Entities.DeliveryService", "DeliService")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("DeliServiceId")
                        .IsRequired()
                        .HasConstraintName("deliverydetail_deliserviceid_foreign");

                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("deliverydetail_ordid_foreign");

                    b.Navigation("Address");

                    b.Navigation("DeliService");

                    b.Navigation("Ord");
                });

            modelBuilder.Entity("Domain.Entities.EventDetail", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("EventDetails")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("eventdetail_eventid_foreign");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("EventDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("eventdetail_productid_foreign");

                    b.Navigation("Event");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.KeyQuestion", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("KeyQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("keyquestion_questionid_foreign");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("Orders")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("order_eventid_foreign");

                    b.HasOne("Domain.Entities.OrderStatus", "OrdStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrdStatusId")
                        .IsRequired()
                        .HasConstraintName("order_ordstatusid_foreign");

                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("Orders")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("order_usrid_foreign");

                    b.Navigation("Event");

                    b.Navigation("OrdStatus");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("orderdetail_ordid_foreign");

                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("orderdetail_prodid_foreign");

                    b.Navigation("Ord");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("Domain.Entities.OrderLog", b =>
                {
                    b.HasOne("Domain.Entities.OrderStatus", "NewStatusOrd")
                        .WithMany("OrderLogs")
                        .HasForeignKey("NewStatusOrdId")
                        .IsRequired()
                        .HasConstraintName("orderlog_newstatusordid_foreign");

                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("OrderLogs")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("orderlog_ordid_foreign");

                    b.Navigation("NewStatusOrd");

                    b.Navigation("Ord");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("product_brandid_foreign");

                    b.HasOne("Domain.Entities.CategoryProduct", "Cate")
                        .WithMany("Products")
                        .HasForeignKey("CateId")
                        .IsRequired()
                        .HasConstraintName("product_cateid_foreign");

                    b.Navigation("Brand");

                    b.Navigation("Cate");
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("productimage_productid_foreign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.CategoryQuestion", "CateQuestion")
                        .WithMany("Questions")
                        .HasForeignKey("CateQuestionId")
                        .IsRequired()
                        .HasConstraintName("question_catequestionid_foreign");

                    b.Navigation("CateQuestion");
                });

            modelBuilder.Entity("Domain.Entities.RatingProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("RatingProducts")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("ratingproduct_prodid_foreign");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("Domain.Entities.ResultSkinTest", b =>
                {
                    b.HasOne("Domain.Entities.SkinType", "SkinType")
                        .WithMany("ResultSkinTests")
                        .HasForeignKey("SkinTypeId")
                        .IsRequired()
                        .HasConstraintName("resultskintest_skintypeid_foreign");

                    b.HasOne("Domain.Entities.SkinTypeTest", "Test")
                        .WithMany("ResultSkinTests")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("resultskintest_testid_foreign");

                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("ResultSkinTests")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("resultskintest_usrid_foreign");

                    b.Navigation("SkinType");

                    b.Navigation("Test");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.ReturnProduct", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("ReturnProducts")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("returnproduct_ordid_foreign");

                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("ReturnProducts")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("returnproduct_usrid_foreign");

                    b.Navigation("Ord");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.ReturnProductDetail", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("ReturnProductDetails")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("returnproductdetail_prodid_foreign");

                    b.HasOne("Domain.Entities.ReturnProduct", "Return")
                        .WithMany("ReturnProductDetails")
                        .HasForeignKey("ReturnId")
                        .IsRequired()
                        .HasConstraintName("returnproductdetail_returnid_foreign");

                    b.Navigation("Prod");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Domain.Entities.SkinTypeTestDetail", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("SkinTypeTestDetails")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("skintypetestdetail_questionid_foreign");

                    b.HasOne("Domain.Entities.SkinTypeTest", "Test")
                        .WithMany("SkinTypeTestDetails")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("skintypetestdetail_testid_foreign");

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Domain.Entities.UseFor", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("UseFors")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("usefor_prodid_foreign");

                    b.HasOne("Domain.Entities.SkinType", "SkinType")
                        .WithMany("UseFors")
                        .HasForeignKey("SkinTypeId")
                        .IsRequired()
                        .HasConstraintName("usefor_skintypeid_foreign");

                    b.Navigation("Prod");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Account", "Usr")
                        .WithOne("User")
                        .HasForeignKey("Domain.Entities.User", "UsrId")
                        .IsRequired()
                        .HasConstraintName("user_usrid_foreign");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("Vouchers")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("voucher_usrid_foreign");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.WarantyOrder", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("WarantyOrders")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("warantyorder_ordid_foreign");

                    b.Navigation("Ord");
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AccountStatus", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.CategoryQuestion", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.DeliveryService", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("EventDetails");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.KeyQuestion", b =>
                {
                    b.Navigation("AnswerUsers");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("DeliveryDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("OrderLogs");

                    b.Navigation("ReturnProducts");

                    b.Navigation("WarantyOrders");
                });

            modelBuilder.Entity("Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("OrderLogs");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EventDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("RatingProducts");

                    b.Navigation("ReturnProductDetails");

                    b.Navigation("UseFors");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Navigation("AnswerUsers");

                    b.Navigation("KeyQuestions");

                    b.Navigation("SkinTypeTestDetails");
                });

            modelBuilder.Entity("Domain.Entities.ReturnProduct", b =>
                {
                    b.Navigation("ReturnProductDetails");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.Entities.SkinType", b =>
                {
                    b.Navigation("ResultSkinTests");

                    b.Navigation("UseFors");
                });

            modelBuilder.Entity("Domain.Entities.SkinTypeTest", b =>
                {
                    b.Navigation("ResultSkinTests");

                    b.Navigation("SkinTypeTestDetails");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("ResultSkinTests");

                    b.Navigation("ReturnProducts");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
