// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250214034527_AutoMigration_20250214104519")]
    partial class AutoMigration_20250214104519
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Property<long>("AccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("accID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccId"));

                    b.Property<short>("AccStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("accStatusID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("'255'::character varying");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("roleID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("AccId")
                        .HasName("Account_pkey");

                    b.HasIndex("AccStatusId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "Account_username_key")
                        .IsUnique();

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AccountStatus", b =>
                {
                    b.Property<short>("AccStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("accStatusID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("AccStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("statusName");

                    b.HasKey("AccStatusId")
                        .HasName("AccountStatus_pkey");

                    b.ToTable("AccountStatus", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("addressID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AddressId"));

                    b.Property<string>("AddDetail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("addDetail");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("country");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("district");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("isDefault");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ward");

                    b.HasKey("AddressId")
                        .HasName("Address_pkey");

                    b.HasIndex("UsrId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<long>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("brandID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BrandId"));

                    b.Property<string>("BrandDesc")
                        .HasColumnType("text")
                        .HasColumnName("brandDesc");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brandName");

                    b.Property<string>("BrandOrigin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brandOrigin");

                    b.Property<bool>("BrandStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("brandStatus");

                    b.HasKey("BrandId")
                        .HasName("Brand_pkey");

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CategoryProduct", b =>
                {
                    b.Property<short>("CateProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("cateProdID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("CateProdId"));

                    b.Property<string>("CateProdName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cateProdName");

                    b.Property<bool>("CateProdStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("cateProdStatus");

                    b.HasKey("CateProdId")
                        .HasName("CategoryProduct_pkey");

                    b.ToTable("CategoryProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CategoryQuestion", b =>
                {
                    b.Property<short>("CateQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("cateQuestionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("CateQuestionId"));

                    b.Property<string>("CateDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cateDesc");

                    b.Property<string>("CateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cateName");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.HasKey("CateQuestionId")
                        .HasName("CategoryQuestion_pkey");

                    b.ToTable("CategoryQuestion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeliveryDetail", b =>
                {
                    b.Property<long>("DeliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("deliID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliId"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("addressID");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createAt");

                    b.Property<string>("DeliPhone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deliPhone");

                    b.Property<long>("DeliServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("deliServiceID");

                    b.Property<bool>("DeliStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("deliStatus")
                        .HasComment("Just manage 2 status: Success / False");

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.HasKey("DeliId")
                        .HasName("DeliveryDetail_pkey");

                    b.HasIndex("AddressId");

                    b.HasIndex("DeliServiceId");

                    b.HasIndex("OrdId");

                    b.ToTable("DeliveryDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeliveryService", b =>
                {
                    b.Property<long>("DeliServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DeliServiceID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliServiceId"));

                    b.Property<string>("ContactService")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contactService");

                    b.Property<string>("DeliServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("DeliServiceStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("deliServiceStatus");

                    b.HasKey("DeliServiceId")
                        .HasName("DeliveryService_pkey");

                    b.ToTable("DeliveryService", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("discountPercent");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("endTime");

                    b.Property<string>("EventDesc")
                        .HasColumnType("text")
                        .HasColumnName("eventDesc");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("eventName");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("startTime");

                    b.Property<bool>("StatusEvent")
                        .HasColumnType("boolean")
                        .HasColumnName("statusEvent");

                    b.HasKey("EventId")
                        .HasName("Event_pkey");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EventDetail", b =>
                {
                    b.Property<long>("EventDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("eventDetailID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventDetailId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("productID");

                    b.HasKey("EventDetailId")
                        .HasName("EventDetail_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("ProductId");

                    b.ToTable("EventDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KeyQuestion", b =>
                {
                    b.Property<short>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("keyID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("KeyId"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<string>("KeyContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyContent");

                    b.Property<short>("KeyScore")
                        .HasColumnType("smallint")
                        .HasColumnName("keyScore");

                    b.Property<short>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("questionID");

                    b.HasKey("KeyId")
                        .HasName("KeyQuestion_pkey");

                    b.HasIndex("QuestionId");

                    b.ToTable("KeyQuestion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<long>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrdId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("eventID");

                    b.Property<DateTime>("OrdDate")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("ordDate");

                    b.Property<short>("OrdStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("ordStatusID");

                    b.Property<double>("TotalOrdPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("totalOrdPrice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("OrdId")
                        .HasName("Order_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("OrdStatusId");

                    b.HasIndex("UsrId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("OrdDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordDetailID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrdDetailId"));

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<double>("SellPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("sellPrice");

                    b.HasKey("OrdDetailId")
                        .HasName("OrderDetail_pkey");

                    b.HasIndex("OrdId");

                    b.HasIndex("ProdId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderLog", b =>
                {
                    b.Property<long>("OrdLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ordLogID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrdLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<short>("NewStatusOrdId")
                        .HasColumnType("smallint")
                        .HasColumnName("newStatusOrdID");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("OrdLogId")
                        .HasName("OrderLog_pkey");

                    b.HasIndex("NewStatusOrdId");

                    b.HasIndex("OrdId");

                    b.ToTable("OrderLog", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderStatus", b =>
                {
                    b.Property<short>("OrdStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("ordStatusID");

                    b.Property<string>("OrdStatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ordStatusName");

                    b.HasKey("OrdStatusId")
                        .HasName("OrderStatus_pkey");

                    b.ToTable("OrderStatus", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("paymentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("orderID");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("paymentAmount");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("paymentMethod");

                    b.HasKey("PaymentId")
                        .HasName("Payment_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("productID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductId"));

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint")
                        .HasColumnName("brandID");

                    b.Property<short>("CateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("cateID");

                    b.Property<double>("CostPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasColumnName("costPrice")
                        .HasDefaultValueSql("'0'::double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingredient");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<short>("ProdStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("prodStatusID");

                    b.Property<string>("ProductDesc")
                        .HasColumnType("text")
                        .HasColumnName("productDesc");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("productName");

                    b.Property<double>("SellPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasColumnName("sellPrice")
                        .HasDefaultValueSql("'0'::double precision");

                    b.Property<int>("Stocks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stocks");

                    b.Property<double?>("TotalRating")
                        .HasColumnType("double precision")
                        .HasColumnName("totalRating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("ProductId")
                        .HasName("Product_pkey");

                    b.HasIndex("BrandId");

                    b.HasIndex("CateId");

                    b.HasIndex("ProdStatusId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.Property<long>("ProdImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("prodImageID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProdImageId"));

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<string>("ProdImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("prodImageUrl");

                    b.HasKey("ProdImageId")
                        .HasName("ProductImage_pkey");

                    b.HasIndex("ProdId");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ProductStatus", b =>
                {
                    b.Property<short>("ProdStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("prodStatusID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("ProdStatusId"));

                    b.Property<string>("ProdStatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("prodStatusName");

                    b.HasKey("ProdStatusId")
                        .HasName("ProductStatus_pkey");

                    b.ToTable("ProductStatus", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<short>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("questionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("QuestionId"));

                    b.Property<long>("AnsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ansID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnsId"));

                    b.Property<short>("CateQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("cateQuestionID");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questionContent");

                    b.HasKey("QuestionId")
                        .HasName("Question_pkey");

                    b.HasIndex("CateQuestionId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Quiz", b =>
                {
                    b.Property<long>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("quizID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QuizId"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<string>("QuizDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quizDesc");

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("quizName");

                    b.HasKey("QuizId")
                        .HasName("Quiz_pkey");

                    b.ToTable("Quiz", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.QuizDetail", b =>
                {
                    b.Property<long>("DetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("detailID");

                    b.Property<short>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("questID");

                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quizID");

                    b.HasKey("DetailId")
                        .HasName("QuizDetail_pkey");

                    b.HasIndex("QuestId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RecommendFor", b =>
                {
                    b.Property<long>("RecForId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("recForID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecForId"));

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<short>("SkinTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("skinTypeID");

                    b.HasKey("RecForId")
                        .HasName("RecommendFor_pkey");

                    b.HasIndex("ProdId");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("RecommendFor", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultDetail", b =>
                {
                    b.Property<long>("ResultDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("resultDetailID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ResultDetailId"));

                    b.Property<short>("KeyId")
                        .HasColumnType("smallint")
                        .HasColumnName("keyID");

                    b.Property<long>("ResultId")
                        .HasColumnType("bigint")
                        .HasColumnName("resultID");

                    b.HasKey("ResultDetailId")
                        .HasName("ResultDetail_pkey");

                    b.HasIndex("KeyId");

                    b.HasIndex("ResultId");

                    b.ToTable("ResultDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultQuiz", b =>
                {
                    b.Property<long>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("resultID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ResultId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createAt");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isDefault");

                    b.Property<short>("Odscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ODScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("OilyDryScore");

                    b.Property<short>("Pnpscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("PNPScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("PigmentedNonPigmentedScore");

                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quizID");

                    b.Property<short>("SkinTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("skinTypeID");

                    b.Property<short>("Srscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("SRScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("SensitiveResistantScore");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<short>("Wtscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("WTScore")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("WrinkledTightScore");

                    b.HasKey("ResultId")
                        .HasName("ResultQuiz_pkey");

                    b.HasIndex("QuizId");

                    b.HasIndex("SkinTypeId");

                    b.HasIndex("UsrId");

                    b.ToTable("ResultQuiz", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnProduct", b =>
                {
                    b.Property<long>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("returnID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReturnId"));

                    b.Property<long>("OrdIdd")
                        .HasColumnType("bigint")
                        .HasColumnName("ordIDd");

                    b.Property<double>("RefundAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("refundAmount");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("returnDate");

                    b.Property<bool>("ReturnStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("returnStatus");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("ReturnId")
                        .HasName("ReturnProduct_pkey");

                    b.HasIndex("OrdIdd");

                    b.HasIndex("UsrId");

                    b.ToTable("ReturnProduct", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnProductDetail", b =>
                {
                    b.Property<long>("ReturnProdDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("returnProdDetailID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReturnProdDetailId"));

                    b.Property<long>("ProdIdre")
                        .HasColumnType("bigint")
                        .HasColumnName("prodIDre");

                    b.Property<long>("ReturnId")
                        .HasColumnType("bigint")
                        .HasColumnName("returnID");

                    b.Property<string>("ReturnImgUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("returnImgUrl");

                    b.Property<short>("ReturnQuantity")
                        .HasColumnType("smallint")
                        .HasColumnName("returnQuantity");

                    b.HasKey("ReturnProdDetailId")
                        .HasName("ReturnProductDetail_pkey");

                    b.HasIndex("ProdIdre");

                    b.HasIndex("ReturnId");

                    b.ToTable("ReturnProductDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reviewID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<long>("ProdId")
                        .HasColumnType("bigint")
                        .HasColumnName("prodID");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reviewContent");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updatedAt");

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.HasKey("ReviewId")
                        .HasName("Review_pkey");

                    b.HasIndex("ProdId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("roleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("roleName");

                    b.Property<bool>("RoleStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("roleStatus");

                    b.HasKey("RoleId")
                        .HasName("Role_pkey");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SkinType", b =>
                {
                    b.Property<short>("SkinTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("skinTypeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("SkinTypeId"));

                    b.Property<string>("SkinTypeCodes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("skinTypeCodes")
                        .HasComment("Mã loại da (ví dụ: \"OSPT\", \"DRNW\").");

                    b.Property<string>("SkinTypeDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skinTypeDesc")
                        .HasComment("Mô tả chi tiết về loại da.");

                    b.Property<string>("SkinTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("skinTypeName")
                        .HasComment("Tên loại da đầy đủ (ví dụ: \"Oily, Sensitive, Pigmented, Tight\").");

                    b.HasKey("SkinTypeId")
                        .HasName("SkinType_pkey");

                    b.ToTable("SkinType", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TreatmentSolution", b =>
                {
                    b.Property<short>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("solutionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("SolutionId"));

                    b.Property<short>("SkinTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("skinTypeID");

                    b.Property<string>("SolutionContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solutionContent");

                    b.HasKey("SolutionId")
                        .HasName("TreatmentSolution_pkey");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("TreatmentSolution", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("UsrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatarUrl");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coverUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerifyToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("emailVerifyToken");

                    b.Property<string>("ForgotPasswordToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("forgotPasswordToken");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<short?>("Gender")
                        .HasColumnType("smallint")
                        .HasColumnName("gender");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("phone");

                    b.Property<short>("RewardPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("rewardPoint")
                        .HasDefaultValueSql("'0'::smallint")
                        .HasComment("0-250: Bronze rank\n250-1500: Silver rank\nOver 1500: Gold rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("UsrId")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "EmailVerifyToken" }, "User_emailVerifyToken_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "User_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ForgotPasswordToken" }, "User_forgotPasswordToken_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "User_phone_key")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.Property<long>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("voucherID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VoucherId"));

                    b.Property<long>("UsrId")
                        .HasColumnType("bigint")
                        .HasColumnName("usrID");

                    b.Property<string>("VoucherDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voucherDesc");

                    b.Property<double>("VoucherDiscount")
                        .HasColumnType("double precision")
                        .HasColumnName("voucherDiscount");

                    b.HasKey("VoucherId")
                        .HasName("Voucher_pkey");

                    b.HasIndex("UsrId");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WarantyOrder", b =>
                {
                    b.Property<long>("WarantyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("warantyID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WarantyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("endDate");

                    b.Property<long>("OrdId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordID");

                    b.HasKey("WarantyId")
                        .HasName("WarantyOrder_pkey");

                    b.HasIndex("OrdId");

                    b.ToTable("WarantyOrder", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.HasOne("Domain.Entities.AccountStatus", "AccStatus")
                        .WithMany("Accounts")
                        .HasForeignKey("AccStatusId")
                        .IsRequired()
                        .HasConstraintName("account_accstatusid_foreign");

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("account_roleid_foreign");

                    b.Navigation("AccStatus");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("Addresses")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("address_usrid_foreign");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.DeliveryDetail", b =>
                {
                    b.HasOne("Domain.Entities.Address", "Address")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("deliverydetail_addressid_foreign");

                    b.HasOne("Domain.Entities.DeliveryService", "DeliService")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("DeliServiceId")
                        .IsRequired()
                        .HasConstraintName("deliverydetail_deliserviceid_foreign");

                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("deliverydetail_ordid_foreign");

                    b.Navigation("Address");

                    b.Navigation("DeliService");

                    b.Navigation("Ord");
                });

            modelBuilder.Entity("Domain.Entities.EventDetail", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("EventDetails")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("eventdetail_eventid_foreign");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("EventDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("eventdetail_productid_foreign");

                    b.Navigation("Event");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.KeyQuestion", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("KeyQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("keyquestion_questionid_foreign");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("Orders")
                        .HasForeignKey("EventId")
                        .HasConstraintName("order_eventid_foreign");

                    b.HasOne("Domain.Entities.OrderStatus", "OrdStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrdStatusId")
                        .IsRequired()
                        .HasConstraintName("order_ordstatusid_foreign");

                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("Orders")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("order_usrid_foreign");

                    b.Navigation("Event");

                    b.Navigation("OrdStatus");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("orderdetail_ordid_foreign");

                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("orderdetail_prodid_foreign");

                    b.Navigation("Ord");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("Domain.Entities.OrderLog", b =>
                {
                    b.HasOne("Domain.Entities.OrderStatus", "NewStatusOrd")
                        .WithMany("OrderLogs")
                        .HasForeignKey("NewStatusOrdId")
                        .IsRequired()
                        .HasConstraintName("orderlog_newstatusordid_foreign");

                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("OrderLogs")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("orderlog_ordid_foreign");

                    b.Navigation("NewStatusOrd");

                    b.Navigation("Ord");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("payment_ordid_foreign");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("product_brandid_foreign");

                    b.HasOne("Domain.Entities.CategoryProduct", "Cate")
                        .WithMany("Products")
                        .HasForeignKey("CateId")
                        .IsRequired()
                        .HasConstraintName("product_cateid_foreign");

                    b.HasOne("Domain.Entities.ProductStatus", "ProdStatus")
                        .WithMany("Products")
                        .HasForeignKey("ProdStatusId")
                        .IsRequired()
                        .HasConstraintName("product_prodstatusid_foreign");

                    b.Navigation("Brand");

                    b.Navigation("Cate");

                    b.Navigation("ProdStatus");
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("productimage_prodid_foreign");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.CategoryQuestion", "CateQuestion")
                        .WithMany("Questions")
                        .HasForeignKey("CateQuestionId")
                        .IsRequired()
                        .HasConstraintName("question_catequestionid_foreign");

                    b.Navigation("CateQuestion");
                });

            modelBuilder.Entity("Domain.Entities.QuizDetail", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Quest")
                        .WithMany("QuizDetails")
                        .HasForeignKey("QuestId")
                        .IsRequired()
                        .HasConstraintName("quizdetail_questid_foreign");

                    b.HasOne("Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizDetails")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("quizdetail_quizid_foreign");

                    b.Navigation("Quest");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Domain.Entities.RecommendFor", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("RecommendFors")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("recommendfor_prodid_foreign");

                    b.HasOne("Domain.Entities.SkinType", "SkinType")
                        .WithMany("RecommendFors")
                        .HasForeignKey("SkinTypeId")
                        .IsRequired()
                        .HasConstraintName("recommendfor_skintypeid_foreign");

                    b.Navigation("Prod");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("Domain.Entities.ResultDetail", b =>
                {
                    b.HasOne("Domain.Entities.KeyQuestion", "Key")
                        .WithMany("ResultDetails")
                        .HasForeignKey("KeyId")
                        .IsRequired()
                        .HasConstraintName("resultdetail_keyid_foreign");

                    b.HasOne("Domain.Entities.ResultQuiz", "Result")
                        .WithMany("ResultDetails")
                        .HasForeignKey("ResultId")
                        .IsRequired()
                        .HasConstraintName("resultdetail_resultid_foreign");

                    b.Navigation("Key");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Domain.Entities.ResultQuiz", b =>
                {
                    b.HasOne("Domain.Entities.Quiz", "Quiz")
                        .WithMany("ResultQuizzes")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("resultquiz_quizid_foreign");

                    b.HasOne("Domain.Entities.SkinType", "SkinType")
                        .WithMany("ResultQuizzes")
                        .HasForeignKey("SkinTypeId")
                        .IsRequired()
                        .HasConstraintName("resultquiz_skintypeid_foreign");

                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("ResultQuizzes")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("resultquiz_usrid_foreign");

                    b.Navigation("Quiz");

                    b.Navigation("SkinType");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.ReturnProduct", b =>
                {
                    b.HasOne("Domain.Entities.Order", "OrdIddNavigation")
                        .WithMany("ReturnProducts")
                        .HasForeignKey("OrdIdd")
                        .IsRequired()
                        .HasConstraintName("returnproduct_ordidd_foreign");

                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("ReturnProducts")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("returnproduct_usrid_foreign");

                    b.Navigation("OrdIddNavigation");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.ReturnProductDetail", b =>
                {
                    b.HasOne("Domain.Entities.Product", "ProdIdreNavigation")
                        .WithMany("ReturnProductDetails")
                        .HasForeignKey("ProdIdre")
                        .IsRequired()
                        .HasConstraintName("returnproductdetail_prodidre_foreign");

                    b.HasOne("Domain.Entities.ReturnProduct", "Return")
                        .WithMany("ReturnProductDetails")
                        .HasForeignKey("ReturnId")
                        .IsRequired()
                        .HasConstraintName("returnproductdetail_returnid_foreign");

                    b.Navigation("ProdIdreNavigation");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Prod")
                        .WithMany("Reviews")
                        .HasForeignKey("ProdId")
                        .IsRequired()
                        .HasConstraintName("comment_prodid_foreign");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("Domain.Entities.TreatmentSolution", b =>
                {
                    b.HasOne("Domain.Entities.SkinType", "SkinType")
                        .WithMany("TreatmentSolutions")
                        .HasForeignKey("SkinTypeId")
                        .IsRequired()
                        .HasConstraintName("treatmentsolution_skintypeid_foreign");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Account", "Usr")
                        .WithOne("User")
                        .HasForeignKey("Domain.Entities.User", "UsrId")
                        .IsRequired()
                        .HasConstraintName("user_usrid_foreign");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.HasOne("Domain.Entities.User", "Usr")
                        .WithMany("Vouchers")
                        .HasForeignKey("UsrId")
                        .IsRequired()
                        .HasConstraintName("voucher_usrid_foreign");

                    b.Navigation("Usr");
                });

            modelBuilder.Entity("Domain.Entities.WarantyOrder", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Ord")
                        .WithMany("WarantyOrders")
                        .HasForeignKey("OrdId")
                        .IsRequired()
                        .HasConstraintName("warantyorder_ordid_foreign");

                    b.Navigation("Ord");
                });

            modelBuilder.Entity("Domain.Entities.Account", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AccountStatus", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.CategoryQuestion", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.DeliveryService", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("EventDetails");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.KeyQuestion", b =>
                {
                    b.Navigation("ResultDetails");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("DeliveryDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("OrderLogs");

                    b.Navigation("Payments");

                    b.Navigation("ReturnProducts");

                    b.Navigation("WarantyOrders");
                });

            modelBuilder.Entity("Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("OrderLogs");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("EventDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("RecommendFors");

                    b.Navigation("ReturnProductDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.ProductStatus", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Navigation("KeyQuestions");

                    b.Navigation("QuizDetails");
                });

            modelBuilder.Entity("Domain.Entities.Quiz", b =>
                {
                    b.Navigation("QuizDetails");

                    b.Navigation("ResultQuizzes");
                });

            modelBuilder.Entity("Domain.Entities.ResultQuiz", b =>
                {
                    b.Navigation("ResultDetails");
                });

            modelBuilder.Entity("Domain.Entities.ReturnProduct", b =>
                {
                    b.Navigation("ReturnProductDetails");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Domain.Entities.SkinType", b =>
                {
                    b.Navigation("RecommendFors");

                    b.Navigation("ResultQuizzes");

                    b.Navigation("TreatmentSolutions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("ResultQuizzes");

                    b.Navigation("ReturnProducts");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
